### ISSUE TITLE
HTML5 section shows alert instead of SVG illustration

### ISSUE THREAD

**Issue by bogdanptr** [Caphyon/awrstudyr#11]
When the HTML5 validator has no errors found, it shows an alert with "no data found" instead of the "success" SVG illustration.

![Mask Group (28)](https://user-images.githubusercontent.com/16166170/66547701-74b98a00-eb48-11e9-9ced-df2f9995dfe1.png)

**Comment by catalinred** [comment]
Fixed by #16
