### ISSUE TITLE
a11y score value rounding

### ISSUE THREAD

**Issue by bogdanptr** [Caphyon/awrstudyr#4]
<img width="591" alt="rounding" src="https://user-images.githubusercontent.com/16166170/54370421-43471180-4680-11e9-99e5-406d0c58eaef.png">
Accessibility score value is not rounded. Happens on both browsers(chrome/firefox).

Can be replicated by running awrstudyr on [this url](https://www.pcmaffey.com/roll-your-own-analytics/)

**Comment by catalinred** [comment]
Fixed with the latest merge.
